services:
  catalogdb:
    container_name: catalog.db
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb

  

