services:
  catalogdb:
    container_name: catalog.db
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb

  basketdb:
    container_name: basket.db
    restart: always
    ports: 
      - "6379:6379"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=basketdb:6379"
      - ASPNETCORE_URLS=http://+:8081
    ports:
      - "8081:8081"
    depends_on:
      - basketdb

  

